spring.application.name=relationaldb
server.port=8081
spring.datasource.url=jdbc:postgresql://140.238.65.12:5432/spotydb
spring.datasource.username=cristian
spring.datasource.password=cristian


logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#configuracion de redis
spring.data.redis.host=localhost
spring.data.redis.port=6379